namespace Ambermoon
{
    // Note: We only add those we need (space, letters and digits are handled as chars).
    public enum Key
    {
        Invalid,
        Left,
        Right,
        Up,
        Down,
        Escape,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        Return,
        Delete,
        Backspace,
        Tab,
        Num0,
        Num1,
        Num2,
        Num3,
        Num4,
        Num5,
        Num6,
        Num7,
        Num8,
        Num9,
        PageUp,
        PageDown,
        Home,
        End
    }
}
