namespace Ambermoon.Data.Enumerations
{
    public enum ButtonType
    {
        // 78 with 32 pixel wide and 13 pixel high
        TurnLeft,
        MoveForward,
        TurnRight,
        StrafeLeft,
        StrafeRight,
        RotateLeft,
        MoveBackward,
        RotateRight,
        MoveUpLeft,
        MoveUp,
        MoveUpRight,
        MoveLeft,
        MoveRight,
        MoveDownLeft,
        MoveDown,
        MoveDownRight,
        Eye,
        Hand,
        Mouth,
        Transport,
        Spells,
        Camp,
        Map,
        BattlePositions,
        Options,
        Empty,
        Yes,
        No,
        Ok,
        Exit,
        BuyHorse,
        BuyRaft,
        BuyBoat,
        BuyItem,
        BuyFood,
        SellItem,
        RepairItem,
        RechargeItem,
        HealAilment,
        HealPerson,
        RemoveCurse,
        Train,
        Grid, // TODO (3x3 blocks, not sure were it was used)
        GiveItem,
        GiveFood,
        GiveGold,
        AskToJoin,
        AskToLeave,
        Attack,
        Defend,
        Flee,
        Stats,
        Inventory,
        UseItem,
        ViewItem, // also show item
        GoldToPlayer,
        FoodToPlayer,
        DropItem,
        DropGold,
        DropFood,
        StoreItem,
        StoreGold,
        StoreFood,
        Lockpick,
        FindTrap,
        DisarmTrap,
        DistributeFood,
        DistributeGold,
        Sleep,
        Ear, // re-hear riddle
        ReadScroll,
        Wait, // hourglass
        Save,
        Load,
        Quit,
        Opt,
        Male, // symbol
        Female // symbol
    }
}
