namespace Ambermoon.Data.Enumerations
{
    public enum MonsterGraphicIndex
    {
        None,
        Gargoyle,
        Undead,
        Demon,
        Orc,
        Lizard,
        Giant,
        Knight,
        MoragDragon,
        Golem,
        Hyrda,
        Magician,
        Minotaur,
        Nera,
        MagicGuard,
        FireDragon,
        Spider,
        Bandit,
        Beast,
        EnergySphere,
        MoranianMagician,
        AntiqueGuard,
        CurseWesp,
        Tornak,
        Gizzek,
        MoragMachine
    }
}
