namespace Ambermoon.Data.Enumerations
{
    public enum Picture80x80
    {
        None,
        ChestClosed,
        Door,
        ChestOpenEmpty,
        Enchantress,
        Healer,
        Horse,
        Innkeeper,
        Librarian,
        Magician,
        Merchant,
        ChestOpenFull,
        Sage,
        Captain,
        Thief,
        Treasure,
        Knight,
        Riddlemouth,
        RestInn,
        RestDungeon,
        RestOutdoor,
        MoragMerchant,
        DwarfMerchant
    }
}
